### PR TITLE
Implement searching password hashes using split database

### LINKED ISSUE #185: Test-PasswordQuality directly with SPLIT database from HIBP
Test-PasswordQuality and the parameter -WeakPasswordHashesSortedFile or -WeakPasswordHashesFile is using the single file, e.g. fom HIBP.

Actually I use two seperate versions of the HIBP File: Single and Split into 00000-FFFFF.txt, the SPLIT files are more performant, when checking how often the hash is in the breached list.

For Data Reduction reasons, it would be nice to have only the split version and a parameter like " -WeakPasswordHashesFilePath"

### PR DESCRIPTION
**Pull request by aseigler**
Resolves #185

### CODE REVIEW

**Comment by aseigler** [comment]
Old way:
```powershell
PS R:\> (Measure-Command { $dsaccounts | Test-PasswordQuality -WeakPasswordHashesSortedFile R:\pwned.txt }).TotalMilliseconds
2141.1098
```
New way:
```powershell
PS R:\> (Measure-Command { $dsaccounts | Test-PasswordQuality -WeakPasswordHashesSortedFilePath R:\hibp_files\ }).TotalMilliseconds
850.2169
```

**Comment by MichaelGrafnetter** [comment]
Hey @aseigler , thx for this nice PR. Could you please update the markdown documentation for the cmdlet as well, perhaps with an example? I am also not sure, if the command would work properly when both `WeakPasswordHashesSortedFile` and `WeakPasswordHashesSortedFilePath` are used.

**Comment by aseigler** [comment]
> Hey @aseigler , thx for this nice PR. Could you please update the markdown documentation for the cmdlet as well, perhaps with an example? 

Sure, no problem.

> I am also not sure, if the command would work properly when both `WeakPasswordHashesSortedFile` and `WeakPasswordHashesSortedFilePath` are used.

This would definitely be an either/or situation, it would make no sense to try to do both in a single command, but checking for that case is simple enough as well.

**Comment by aseigler** [comment]
Ready for review again.

**Comment by aseigler** [comment]
Bump. @MichaelGrafnetter

**Pull request merged**
