### PR TITLE
Add FIDO key test, change while to use position instead of PeekChar().

### PR DESCRIPTION
**Pull request by aseigler**

### CODE REVIEW

**Comment by MichaelGrafnetter** [comment]
Thanks for the test! What FIDO device does the key come from? YubiKey 5?

**Comment by aseigler** [comment]
Correct, YubiKey 5.  In the case where key.Usage = KeyUsage.FIDO, the key.KeyMaterial is an authenticator data structure, as defined here:  https://www.w3.org/TR/webauthn/#sec-authenticator-data

**Comment by MichaelGrafnetter** [comment]
Thanks. I will try to implement a KeyMaterial parser in Summer. Are you using the KeyCredential code for any specific use case? I am asking because PowerShell cmdlets for msDS-KeyCredentialLink auditing and also forging/injection are also on my TODO list for this Summer. Do you know of any other on-prem AD tools for this purpose?

**Comment by aseigler** [comment]
I am currently working on a KeyMaterial parser for FIDO usage, it is fairly straightforward JSON encoded. The attested credential data and the extension data within the authenticator data however are CBOR encoded which is a bit more complicated. My usage currently is simply educational/exploratory. I don't know of any other existing tools.

**Comment by MichaelGrafnetter** [comment]
Great! Send me another PR please, once you are finished. CBOR? Hooray, yet another data representation format one must deal with when digging deep into AD, next to JSON, XML, ASN.1, NDR, LDIF etc.

**Comment by MichaelGrafnetter** [comment]
Hi @aseigler , are you sure that the sample data is OK? The [CUSTOM_KEY_INFORMATION](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/701a55dc-d062-4032-a2da-dbdfc384c8cf) in the FIDO key you provided only has 15 bytes instead of 16, meaning that the Reserved field only has 9 bytes instead of 10.

**Comment by aseigler** [comment]
It's definitely good data from a real, working login, not something I stitched together myself. I hadn't looked at CUSTOM_KEY_INFORMATION yet, I had focused on [KEY_USAGE_FIDO](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/d5948ab9-8993-4066-a175-851af361ea7f) and have a full working parser but it's dependent on two external libraries for JSON and CBOR. I have noticed several inconsistencies with this area of documentation and plan on submitting more documentation bugs against them.

**Comment by MichaelGrafnetter** [comment]
Thanks, @aseigler . Just checking. Yep, the documentation is terrible and missing many important details. As one MS employee stated, it contains explanations by alien hybrids for robot lawyers. BTW, are you using [System.Runtime.Serialization.Json](https://www.nuget.org/packages/System.Runtime.Serialization.Json/) or NewtonSoft.Json? I would prefer the first option if possible.

**Comment by aseigler** [comment]
It's currently using Newtonsoft.Json and PeterO.CBOR, only because those are the ones I am most familiar with, but I am open to whatever as long as I can get it to work.

**Comment by MichaelGrafnetter** [comment]
Thx, @aseigler, looking forward to a PR then. No need to change things if it's already working.

**Comment by aseigler** [comment]
If you're good with those dependencies I will have it over shortly.

**Pull request merged**
